# Module-3 Numeric & Scientific Computing with Python

# Data sccience is a brance of computer sciene where we study how to store,use and anylyze data for deriving information from it.

Shortcuts

# * NumPy stand for Numerical Python.It is a Python Library for working with an array
* In python , we use the list for purpose of the array but its slow to process.
Numpy array is a powerful N-Dimensional array and use in linear agebra,fourier tranform and random numer capabilities.
* it provides an array object much faster than traditional Python lists.
* NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely .
  
Type of Array 

1)One Dimensional Array 
2)Multi-Dimensional Array 



# Create a one Dimensional array module

In [4]:
import array as ar
arr=ar.array('i',[9,5,7,3,4])
print(arr)
print(type(arr))

array('i', [9, 5, 7, 3, 4])
<class 'array.array'>


# Create a one-Dimensional Array using Numpy

In [9]:
import numpy as np
ar=np.array([1,2,3,4,5])
print('One Diensional Array')
print(ar)
print(type(ar))
print(ar.shape)

One Diensional Array
[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [16]:
#Get the data type of an array
print(ar.dtype)


int64
8


In [18]:
#To get the size of an array and itemsize
print(ar.size)
print(len(ar))
print(ar.itemsize)
print(ar.nbytes) #itemsize+size

5
5
8
40


In [14]:
# ndim-Number of Dimension in the array
print(ar.ndim)

1


In [28]:
arr=np.array([1.5,2.6,2.1,4.5])
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print('size of array ',arr.size)
print('item_size',arr.itemsize)
print('byte of array',arr.nbytes)#itemsize+size

[1.5 2.6 2.1 4.5]
<class 'numpy.ndarray'>
(4,)
float64
size of array  4
item_size 8
byte of array 32


In [30]:
#to create a complex array using numpy 
ar1=np.array([20+2j,3+1j,5+2j])
print(ar1)
print(ar1.dtype)
print(ar1.size)
print(ar1.itemsize)
print(ar1.nbytes)

[20.+2.j  3.+1.j  5.+2.j]
complex128
3
16
48


In [35]:
arr=np.array([1,5,2,6,2,1,4,5])
print(arr)
print(type(arr))
print(arr.dtype)

[1 5 2 6 2 1 4 5]
<class 'numpy.ndarray'>
int64


In [39]:
#How to access the Numpy Element
print(arr[0])
print(arr[0:5])

1
[1 5 2 6 2]


In [41]:
#replacing the array element 
arr[1]=30
print(arr)

[ 1 30  2  6  2  1  4  5]


In [42]:
print('sum of array is',sum(arr))
print('Maximum Element in the Array ',max(arr))
print('Minimum Element in the Array ',min(arr))

sum of array is 51
Maximum Element in the Array  30
Minimum Element in the Array  1


In [43]:
#append 
arr1=np.array([10,20,30])
np.append(arr,arr1)

array([ 1, 30,  2,  6,  2,  1,  4,  5, 10, 20, 30])

In [47]:
#Arithmetic Operation 
print(arr)
print('Addition of: ',arr+3)

[ 1 30  2  6  2  1  4  5]
Addition of:  [ 4 33  5  9  5  4  7  8]


In [49]:
#arange- array range of value 
ar2=np.arange (10)
print('range of ',ar2)

range of  [0 1 2 3 4 5 6 7 8 9]


In [53]:
# to create and display the string array 
ar3=np.array(['app','bat','cat','dog'])
print(ar3)
print(ar3.dtype)
print(ar3.size)
print(ar3.itemsize)
print(ar3.nbytes)

['app' 'bat' 'cat' 'dog']
<U3
4
12
48


In [57]:
da=np.arange(12)
print('Array is :',da)
#To Change array data type
print(np.array(da,dtype='float'))

Array is : [ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [58]:
#slicing
print(da[::-1])

[11 10  9  8  7  6  5  4  3  2  1  0]


In [62]:
#sort the array Element
print('Befor sort',arr)
ar5=np.sort(arr)
print('After sort',ar5)

[ 1 30  2  6  2  1  4  5]
[ 1  1  2  2  4  5  6 30]


# Deep copying :- 
* This method makes a complete copy of an existing array and its elemnts
* When the newly created array is modified , it will not affect the existing array or vice versa


In [70]:
#Difference Between Deep copy and Shallow copy 
a=np.arange(3,12)
b=a.copy()
print('Original Array is ',a)
print('*'*60)
b[1]=16

print('Original Array is ',a)
print('*'*60)
print('Modified Array is ',b)



Original Array is  [ 3  4  5  6  7  8  9 10 11]
************************************************************
Original Array is  [ 3  4  5  6  7  8  9 10 11]
************************************************************
Modified Array is  [ 3 16  5  6  7  8  9 10 11]


#Shallow Copy  view 

In [71]:
#Shallow Copy 
a=np.arange(3,12)
b=a.view()
print('Original Array is ',a)
print('*'*60)
b[1]=16

print('Original Array is ',a)
print('*'*60)
print('Modified Array is ',b)

Original Array is  [ 3  4  5  6  7  8  9 10 11]
************************************************************
Original Array is  [ 3 16  5  6  7  8  9 10 11]
************************************************************
Modified Array is  [ 3 16  5  6  7  8  9 10 11]
